Only squeeze dimensions that are beyond the list of dims specified in Field
scipp/scippnexus pull request #32
Opened 2022-06-01 13:44 UTC by nvaytet

2022-06-01 13:51 UTC, jl-wynen commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
How do you know that the order is correct?

2022-06-01 13:57 UTC, SimonHeybrock requested changes

2022-06-01 14:05 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
Yes, I am not sure I grasped all the logic.

So how do you know that you need to put the `time` as the first element here? https://github.com/scipp/scippnexus/blob/main/src/scippnexus/nxlog.py#L34

Because of the comment "The outermost axis in NXlog is pre-defined to 'time' (if present)." ?

2022-06-01 14:06 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
In your example above, if you have `shape=[1,2,1,1]` and `dims=['x', 'y']`, how do you know what's what?

2022-06-01 14:09 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
I think we either need to raise in all cases, or adopt a convention (e.g., dims apply from the left). But swapping things around is broken regardless of the conversion, isn't it?

2022-06-01 14:12 UTC, jl-wynen commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
Does the file contain enough information to name all dimensions? In that case, we could pass the full list of dims and shape to `Field` and squeeze length-1 dims only after processing.

2022-06-01 14:15 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
> Does the file contain enough information to name all dimensions?

No. It is Nexus, so the answer is no, you have to guess.

2022-06-01 15:07 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
Maybe we should just not squeeze?

2022-06-02 05:08 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                self._shape = ([1] * (len(self._dims) - len(self._shape))) + self._shape
That is not an option, because Nexus treats `shape=()` and `shape=(1,)` interchangeably.

2022-06-07 05:21 UTC, SimonHeybrock commented on src/scippnexus/nxdata.py
> +        return self._try_guess_dims(name)
Why moved to function?

2022-06-07 07:25 UTC, nvaytet commented on src/scippnexus/nxdata.py
> +        return self._try_guess_dims(name)
Because I am using it in two places: here and 5 lines above.

2022-06-07 08:09 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                self._shape = [size for size in self._shape if size > 1]
Why is this dropping 0s now?

2022-06-07 08:10 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +            self._shape = [size for size in self._shape if size > 1]
Why dropping 0s?

2022-06-07 08:11 UTC, SimonHeybrock commented on tests/nxdata_test.py
> +
Won't we run into this systematically with `NXlog`, where we hard-code the outer axis?

2022-06-10 05:18 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].reshape(shape)
This looks very dangerous. It could hide some potentially really bad bugs.

2022-06-10 07:57 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].reshape(shape)
So I tried for a while yesterday to add an extra slice to `source_sel` if there were some dimensions that needed squeezing, but it was simply not working.

As it turns out, I just tried the simple example again at home last night, and it magically worked:
```Py
import numpy as np
import h5py

with h5py.File('my_hdf5_file.h5', 'w') as f:
    dset = f.create_dataset("dset", (5, 2), dtype='int64')
    arr = np.ones((5,), dtype='int64')
    dset.read_direct(arr, np.s_[:, 0])
    print(arr)
```

Difference: `h5py=3.1.0` at work (because of the `<3.2` pinning due to mantid), `h5py=3.4.0` at home :-(

2022-06-10 07:58 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].reshape(shape)
Can you find out if that is a deliberate fix on their side? If so, then we could bump the required version.

2022-06-10 08:54 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].reshape(shape)
This? https://github.com/h5py/h5py/pull/1796

2022-06-13 04:22 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].reshape(shape)
👍 can you add a comment with the h5py version in our code?

2022-06-13 04:33 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +
Why is this necessary?

2022-06-13 04:33 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].squeeze()
Does `h5py.Dataset.squeeze` trigger a load if the data? If not, i.e., if it is cheap, then I don't the the point of `try`/`except` --- just always squeeze, and avoid most of the lengthy comment (and more importantly the "control-flow-via-exceptions" anti-pattern)?

2022-06-13 09:09 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].squeeze()
I don't think `h5py.Dataset.squeeze` exists?
The point of the try/except is that I think when you use `read_direct` you are not making a copy, while when assigning the `self._dataset[index]` to the `.values` you are making a copy? So better to try and use `read_direct` if you can.
But maybe I understood wrong?

2022-06-13 09:12 UTC, nvaytet commented on src/scippnexus/nxobject.py
> +
I was getting errors in `read_direct` when trying to read in a NXlog with shape 0.
And I thought since there is nothing to load anyway, I could just return the empty variable early?

2022-06-13 10:05 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +                variable.values = self._dataset[index].squeeze()
No that is fine. If it does not exist then what you do is the only option.

2022-06-13 10:06 UTC, SimonHeybrock commented on src/scippnexus/nxobject.py
> +
👍 I vaguely remember I had this is with `read_direct` before.

2022-06-13 11:17 UTC, merged